- builder.js
- index.html
I have added a dropdown to the textbox where a local build name can be entered, just like in item selection.
This makes the feature usable for people who cannot remember every build name they've ever saved.
> Add Dropdown for Local Builds

- builder/index.html
- css/sq2bs.css
- js/sq2bs.js
- js/sq2display.js
**Additions (+):**
- Reset Button
**Changes (Δ):**
- Margin change in item dropdown div parents to prevent item dropdowns from reaching sides of screen
**Deletions (-):**
- Gears photo (taking up space) in level choice/reset button/copy buttons block
> Reset button

- crafter/index.html
- js/crafter.js
**Additions(+): **
- Copy Hash button + feature
**Changes(Δ):**
- CR item now gets calculated/crafted upon input/button presses that would change the CR item
- Typing inputs switched to dark 10 from dark 5
- Small column changes to make button boxes look better 
**Deletions(-):**
- Removed Craft button (because of automatic crafting upon input)
> Crafter copy hash

- builder/index.html
- css/wynnstyles.css
- js/sq2display.js
Changed base dps display to use an icon instead of "base dps"
#25
> changed base dps display to be an icon

- builder/index.html
- css/dev.css
- css/sq2bs.css
- dev/index.html
- items_adv/items_2_help.html
- js/custom.js
- js/customizer.js
- js/dev.js
- js/sq2builder.js
- wynnfo/scripts/main.js
Create Documentation Page
- /dev/
- documentation info on build links, CR items, CI items
> Documentation

- builder/index.html
- js/sq2bs.js
- js/sq2display.js
> Re-enable melee breakdown

- builder/index.html
- js/builder.js
> Stack print

- js/atree.js
- js/builder_graph.js
- js/computation_graph.js
ValueCheckComputeNode: checks the value of its computed function before deciding to send state updates
possibly do this for all item slots but its kinda doom rn since update items does not exist
> ComputeNode subclass that will defer updates if its value did not change

- js/crafter.js
> Restore crafter to working condition i think

- js/builder_graph.js
> Fix crafted accessories apparently

- js/atree.js
> Atree abil hotfix

- crafter/index.html
- js/display.js
> Fix crafter UI inconsistencies

- js/atree_constants.js
> fixed stronger meteor and windsweeper w/ thunstom

- js/builder_graph.js
- js/computation_graph.js
- js/display.js
condense some code in display.js
fix ELS display bug
add debugging tools to compute graph
> Display cleanup

- js/atree.js
Forgot to add this one in my main PR for atree tooltips
> dependencies in atree tooltips

- builder/doc.html
- js/computation_graph.js
> Add debug flag to fix compute graph memory leak

- js/display.js
> Make spellcost floating point

- builder/index_full.html
- js/atree.js
- js/utils.js
> relocate ability toggles and sliders to active boosts section

- js/atree.js
- js/builder_graph.js
- js/computation_graph.js
so u can delete weapon and switch to the same class weapon and keep tree
> Don't update the ability tree when NONE weapon is selected

- js/display.js
- js/utils.js
> Fix crafted accessory durability display

- js/atree.js
Probably. I have no hard evidence that this works, but like it should work...? Can't test for this on a local environment because load times are too fast, and can't test for this on my own private pages because this code isn't designed for how my pages deployment works.
> fix load issues with atree images

- css/sq2bs.css
so mobile browsers don't zoom
hopefully
would like someone to verify that this works before merging... idk if any of us are experiencing this issue tho.. maybe just YOLO it
> Make text on small screens cap at 16px min size

- css/items.css
- items/index.html
- js/items.js
- media/icons/trash.svg
- Default item types to none selected
- Improved display for invalid searches
- Can delete filters
- Can exclude filters (more user friendly than max 0)
- Removed a few filters from the list that no longer exist in the back end
> misc atlas improvements

- js/items.js
- js/query.js
- Exclude filters actually work now lol
- Empty filters don't cause a hissy fit
- Rainbow Spell Damage works now
- Fixed IDs and Custom Skin have been removed from the filter list
> Atlas hotfixes

- js/builder/atree_constants.js
Split from the 2.0.1 push due to popular request
> Update atree_constants.js to 2.0 hotfix 6

- ingreds_clean.json
Removed Strange Trinket's 4 def req (that it doesn't actually have)
> Fix Strange Trinket

- js/build_utils.js
> Fix behavior of -cost and +cost to match ingame rolling

- css/search.css
- ingredients/index.html
- ingredients_adv/index.html
- js/build_utils.js
- js/craft.js
- js/ingredients.js
- js/ingredients_adv.js
- js/items.js
- js/items_adv.js
- js/query.js
- js/search.js
- js/search_adv.js
- Stops sort keys from piling up over time
- Clear outdated search entries
- Adds ingredient searching
- This mainly modifies the already present well-writen item searching to use ingredient objects/queries, and moving common code to a base file (ex: search.js)
> Searching Changes
